/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_loadimage_HelloJni */

#ifndef _Included_com_example_loadimage_HelloJni
#define _Included_com_example_loadimage_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_loadimage_HelloJni
 * Method:    printStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_loadimage_HelloJni_printStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
